name: Test PR

on: pull_request

jobs:
  build:
    name: Test PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.23"
      - name: Run tests
        run: uv run python3 -m unittest
